############################
## CHANGE THESE
############################

baseURL: "https://s-lasch.github.io/qubt-blog"
title: Blog

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
  math:
    enable: true
