############################
## Author
############################

author:
  name: s-lasch
  image: author.png
  greeting: "*A personal blog for all things data and ML*"
#  icon: ":wave:"


############################
## Links
############################

links:
  - github: https://github.com/s-lasch/qubt-blog
#  - website:
  - linkedin: https://linkedin.com/in/steven-l-lasch
  - link: https://steven-lasch.com#projects
  # - x-twitter: 
  # - mastodon:
  # - instagram: 
  # - reddit: 
  # - telegram: 
  # - whatsapp: 
  # - signal: 
  # - codepen: 
  # - dev: 
  # - email: 
  # - discord: 
  # - orcid: 
  # - slack: 
  # - stack-overflow: 
  # - twitch: 
  # - patreon: 
  # - soundcloud: 
  # - dribbble: 
  # - stack-exchange: 
  # - tiktok: 
  # - youtube: 
  # - keybase: 
  # - flickr: 
  # - tumblr: 
  # - kickstarter: 
  # - snapchat:
  # - bluesky: 
  # - bitbucket: 
  # - bandcamp: 
  # - etsy: 
  # - spotify: 
  # - pinterest: 
  # - strava: 
  # - untappd: 
  # - skype: 
  - medium: https://medium.com/@stevenlasch17
  # - foursquare: 
  # - apple: 
  # - amazon:
  # - google:
  # - paypal:
  # - windows:

###############################
## OpenGraph & Twitter Cards
###############################

title: qubt-blog
description: "Site build with Qubt & Hugo"
images:
  - thumbnail.png
